import {
  CONSOLE_STATUS_LABELS,
  consoleLinkHref,
  consoleTaskKey,
  type ConsoleTask,
} from "@/lib/console/model";

/**
 * Coding-agent handoff: a Console entry becomes a file package the architect
 * drops into the repo folder where their agent runs (Cursor, Claude Code,
 * Codex, Muse Code - all consume files). No auth, no network, DOM-free.
 *
 * Layout the panel writes:
 *   gravenx/TASK-CX-XXXX.md   the work item - goal, links, notes, activity
 *   gravenx/media/<shot>      screenshots alongside, referenced by name
 */

export const AGENT_DROP_DIR = "gravenx";
export const AGENT_DROP_MEDIA_DIR = "gravenx/media";

export interface AgentDropFile {
  path: string;
  text: string;
}

export function agentTaskFilename(task: Pick<ConsoleTask, "id" | "createdAt">): string {
  return `TASK-${consoleTaskKey(task)}.md`;
}

function metaLine(task: ConsoleTask): string {
  const bits = [
    `\`${consoleTaskKey(task)}\``,
    `kind ${task.kind ?? "task"}`,
    `status ${CONSOLE_STATUS_LABELS[task.status]}`,
    `priority ${task.priority}`,
  ];
  if (task.owner) bits.push(`owner ${task.owner}`);
  if (task.dueDate) bits.push(`due ${task.dueDate}`);
  return `> GRAVENX Console · ${bits.join(" · ")}`;
}

function linksSection(task: ConsoleTask): string {
  if (task.links.length === 0) return "None - standalone Console item.";
  return task.links
    .map((l) => `- **${l.surface}** · ${l.label} · studio: \`${consoleLinkHref(l)}\``)
    .join("\n");
}

function notesSection(task: ConsoleTask): string {
  if (task.notes.length === 0) return "None.";
  return task.notes
    .map((n) => `### ${new Date(n.at).toLocaleString()}\n\n${n.text.trim()}`)
    .join("\n\n");
}

/** The TASK.md file: everything an agent needs, nothing it must fetch. */
export function buildAgentTaskMd(task: ConsoleTask, attachmentNames: string[] = []): string {
  const shots =
    attachmentNames.length === 0
      ? "None."
      : attachmentNames.map((n) => `- \`${AGENT_DROP_MEDIA_DIR}/${n}\``).join("\n");
  const activity = [...task.history]
    .slice(-10)
    .map((h) => `- ${h.what} (${new Date(h.at).toLocaleString()})`)
    .join("\n");
  return [
    `# ${task.title}`,
    "",
    metaLine(task),
    "",
    "## Goal",
    "",
    task.body?.trim() ? task.body.trim() : "_No description yet - clarify with the architect before implementing._",
    "",
    "## Linked canvas items",
    "",
    linksSection(task),
    "",
    "## Notes",
    "",
    notesSection(task),
    "",
    "## Screenshots",
    "",
    shots,
    "",
    "## Recent activity",
    "",
    activity || "None.",
    "",
    "---",
    "_Generated by GRAVENX Console. Implement the smallest diff that satisfies the Goal, match repo conventions, run the relevant tests, then report files changed and how to verify._",
    "",
  ].join("\n");
}

/** Short paste-prompt: clipboard → agent chat, pointing at the dropped file. */
export function buildAgentPrompt(task: Pick<ConsoleTask, "id" | "createdAt" | "title">): string {
  const file = `./${AGENT_DROP_DIR}/${agentTaskFilename(task)}`;
  return [
    `Implement the GRAVENX task in ${file} ("${task.title}") in this repo.`,
    "",
    "Read the whole file first - Goal, Linked canvas items, Notes, Screenshots.",
    "Ask before changing scope; keep the diff minimal and follow repo conventions.",
    "Run the relevant tests, then report files changed and how to verify.",
  ].join("\n");
}

/** Text files for the drop. Media travels as Blobs via the panel. */
export function buildAgentDrop(task: ConsoleTask, attachmentNames: string[] = []): AgentDropFile[] {
  return [{ path: `${AGENT_DROP_DIR}/${agentTaskFilename(task)}`, text: buildAgentTaskMd(task, attachmentNames) }];
}
