import type { Experience } from "./model";
import { buildOdaManifest } from "./model";
import { screenBehaviors } from "./behavior";
import { apiImpact } from "./systemBridge";
import { schemaDelta } from "./proposed";

/**
 * EPIC 10 - build-instruction generator. Machine-readable artifacts
 * (manifest, delta, impact) render into one structured markdown spec the
 * architect pastes into Cursor / Claude Code / Codex. Deterministic:
 * same experience, same spec, stamped with the experience version.
 */

function bullets(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

export function buildSpec(exp: Experience): string {
  const manifest = buildOdaManifest(exp);
  const delta = schemaDelta(exp);
  const impact = apiImpact(exp);
  const behaviors = screenBehaviors(exp);
  const L: string[] = [];

  L.push(`# BUILD REQUEST - ${exp.name}`, "");
  L.push(`Generated by GRAVENX Wireframe Studio · experience v${exp.version} · status ${exp.status}`, "");
  L.push(`## Application`, "");
  L.push(`${exp.name} - ${exp.screens.length} screen${exp.screens.length === 1 ? "" : "s"}, ${exp.components.length} components${exp.domain ? ` · domain ${exp.domain}` : ""}.`, "");

  L.push(`## Screens`, "");
  if (exp.screens.length === 0) L.push("_No screens yet._", "");
  for (const s of exp.screens) {
    const comps = exp.components.filter((c) => c.parentId === s.id);
    L.push(`### ${s.name}${s.route ? ` (${s.route})` : ""}`);
    if (comps.length === 0) {
      L.push("_No components yet._", "");
      continue;
    }
    for (const c of comps) {
      const bits: string[] = [c.kind];
      if (c.label) bits.push(`"${c.label}"`);
      if (c.bindingState === "existing" && c.binding?.object) {
        bits.push(`binds ${c.binding.field ? `${c.binding.object}.${c.binding.field}` : c.binding.object}`);
      } else if (c.bindingState === "proposed" && c.proposedField) {
        bits.push(`proposes ${c.proposedField.object}.${c.proposedField.apiName} (${c.proposedField.type})`);
      } else if (c.bindingState === "external") {
        bits.push(`external: ${c.binding?.externalLabel ?? c.binding?.object ?? "unspecified"}`);
      }
      if (c.validation?.required) bits.push("required");
      if (c.interaction) bits.push(`on ${c.interaction.trigger} → ${c.interaction.action}${c.interaction.target ? ` ${c.interaction.target}` : ""}`);
      L.push(`- ${bits.join(" · ")}`);
    }
    L.push("");
  }

  L.push(`## Schema delta`, "");
  if (delta.length === 0) L.push("_No bindings yet._", "");
  for (const d of delta) {
    L.push(`### ${d.object}`);
    if (d.existing.length > 0) {
      L.push("Existing fields:", bullets(d.existing.map((f) => `\`${f}\``)), "");
    }
    for (const p of d.proposed) {
      const extra = p.values?.length ? ` values: ${p.values.join(" | ")}` : "";
      const precision = p.precision ? `(${p.precision}${p.scale ? `,${p.scale}` : ""})` : "";
      L.push(`- NEW \`${p.object}.${p.apiName}\` ${p.type}${precision} - ${p.label}${p.required ? " (required)" : ""}${extra}`);
    }
    L.push("");
  }

  L.push(`## API contracts`, "");
  const withApi = impact.filter((s) => s.reads.length + s.writes.length + s.externals.length > 0);
  if (withApi.length === 0) L.push("_No explicit API refs - see bindings above._", "");
  for (const s of withApi) {
    L.push(`### ${s.screenName}`);
    for (const r of s.reads) L.push(`- READ \`${r}\``);
    for (const w of s.writes) L.push(`- WRITE \`${w}\``);
    for (const e of s.externals) L.push(`- EXTERNAL \`${e}\``);
    L.push("");
  }

  if (behaviors.length > 0) {
    L.push(`## Behavior`, "");
    for (const g of behaviors) {
      L.push(`### ${g.screenName}`);
      for (const i of g.items) {
        L.push(`- ${i.label}: on ${i.trigger} → ${i.action}${i.target ? ` ${i.target}` : ""}${i.dangling ? " (⚠ dangling navigation)" : ""}`);
      }
      L.push("");
    }
  }

  if (exp.journeys.length > 0) {
    L.push(`## Journeys`, "");
    const names = new Map(exp.screens.map((s) => [s.id, s.name]));
    for (const j of exp.journeys) {
      L.push(`### ${j.name}`);
      j.screenIds.forEach((id, i) => L.push(`${i + 1}. ${names.get(id) ?? id}`));
      L.push("");
    }
  }

  if (manifest.implements.length + manifest.consumes.length + manifest.emits.length > 0) {
    L.push(`## Asset contract (ODA-aligned, advisory)`, "");
    if (manifest.implements.length > 0) L.push(`Implements: ${manifest.implements.join(", ")}`);
    if (manifest.consumes.length > 0) L.push(`Consumes: ${manifest.consumes.join(", ")}`);
    if (manifest.emits.length > 0) L.push(`Emits: ${manifest.emits.join(", ")}`);
    L.push("");
  }

  L.push(`## Build order`, "");
  L.push("1. Create proposed fields (schema delta above).", "2. Wire reads per screen (API contracts).", "3. Implement behavior intents in screen order.", "4. Walk each journey end to end.");
  return L.join("\n");
}
